services:
    server:
        build: .
        ports:
            - 9000:8000
        restart: always
        command: npm run tailwind:watch
        volumes:
            - rodovale:/app
        develop:
            watch:
                - action: sync
                  path: ./app
                  target: ./app
                  ignore:
                      - vendor/
                - action: rebuild
                  path: .

volumes:
    rodovale:
